### ISSUE TITLE
Use mlprogram instead of neuralnetwork

### ISSUE THREAD

**Issue by Volutionn** [dneprDroid/DeformConv2d-Metal#1]
Hi @dneprDroid, thanks a lot for your work and for sharing this custom layer!

I'm facing a bit of a loop. The model I'm trying to convert uses `grid_sample`, which requires the minimum deployment target to be at least iOS 15. However, when I set `convert_to="neuralnetwork"`, it requires the target to be below iOS 15.

Is there a way to use `mlprogram` instead of `neuralnetwork`? What's the reason we need to use `neuralnetwork` specifically?

Thanks again!

**Comment by dneprDroid** [comment]
Hi, currently custom layers are only supported in `neuralnetwork` format, but you can use this custom layer for `grid_sample` (so you don't need to convert your model to `mlprogram` format):
https://github.com/dneprDroid/pytorch-coreml-custom-layer-example

The note from official docs:
https://apple.github.io/coremltools/docs-guides/source/custom-operators.html

> Custom layers are supported when the conversion is targeted at the “Neural Network” backend. They are not available when using the [ML Programs](https://apple.github.io/coremltools/docs-guides/source/convert-to-ml-program.html) backend.

**Comment by Volutionn** [comment]
Thanks @dneprDroid, it makes sense now! Your custom layer resolved the issue, so I'm going to close this
